### ISSUE TITLE
pgen command not working and not giving any message besides Socket is closed

### ISSUE THREAD

**Issue by q8tywolf** [ozum/pg-generator#70]
Hello 

I would like to thank you on this package very useful, and extremely handy,

I have been using it on previous version but recently have the following problem, 

when I run the pgen command I get the internal command is about to executed but no feed back, 

info: Executing command: pgen.js exec sequelize-main-template --host 192.168.0.13 --port 6432 --user admin --database mydb --schema main --target src/models/main --log info --extension nunj.html --indent 4 --env development

so I copied the command and it asks for a password, and then it says 
Socket is closed

Can you please help

**Comment by ozum** [comment]
I cannot repeat the problem. Did you possibly mistype the port? `6432` instead of default `5432`?

**Comment by q8tywolf** [comment]
I am using a docker instance of PostgreSQL, so am able to connect to PostgreSQL from my node, java and IDE Applications, but when I use the package to generate the models, it keeps saying the socket is closed. 

docker exposes the PostgreSQL instance on the host IP, with 6432 port as specified in the docker compose yml file


docker compose file
```
version: "3.7"
networks:
  app_router:
    driver: bridge
    ipam:
      config:
        - subnet: 172.6.10.0/24
services:
  app-db:
    container_name: app_db
    restart: always
    build:
      context: .
      dockerfile: postgres.Dockerfile
    networks:
      app_router:
        ipv4_address: 172.6.10.100
    volumes:
      - ./postgres/sqldump.sql:/docker-entrypoint-initdb.d/init.sql
      - ${POSTGRES_HOME}:/home
      - app_data:/var/lib/postgresql/data
    ports:
      - "6432:5432" #postgres port
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: mydb
      PGDATA: /var/lib/postgresql/data
```
